image: dart

pipelines:
  default:
    - step:
        name: analyze
        script:
          - dart pub upgrade
          - dart run metrics_for_dart_code:metrics lib -r checkstyle > checkstyle-result.xml
        after-script:
          - pipe: atlassian/checkstyle-report:0.3.1
