name: metrics_for_dart_code
version: 1.0.0
description: Software analytics tool that helps developers analyse and improve software quality.
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

platforms:
  linux:
  windows:
  macos:

dependencies:
  analyzer:
  analyzer_plugin:
  ansicolor:
  args:
  collection:
  crypto:
  file:
  glob:
  html:
  http:
  meta:
  metrics_for_dart_code_presets:
    git:
      url: "https://github.com/ladans-io/metrics_for_dart_code_presets"
  path:
  platform:
  pub_updater:
  source_span:
  uuid:
  xml:
  yaml:

dev_dependencies:
  coverage:
  intl:
  lints:
  mocktail:
  test:

  # internal package, used only in tests data
  # test_lints:
  #   path: ./test/resources/test_lints

executables:
  metrics:
