name: metrics_for_dart_code
version: 1.1.0
description: Improves software quality.
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

platforms:
  linux:
  windows:
  macos:

dependencies:
  analyzer:
  analyzer_plugin:
  ansicolor: ^2.0.1
  args: ^2.0.0
  collection: ^1.16.0
  crypto: ^3.0.0
  file: ^7.0.0
  glob: ^2.0.1
  html: ">=0.15.0 <1.0.0"
  http: ^1.0.0
  meta: ^1.7.0
  metrics_for_dart_code_presets:
    git:
      url: "https://github.com/ladans-io/metrics_for_dart_code_presets"
  path: ^1.8.0
  platform: ^3.1.0
  pub_updater: ^0.4.0
  source_span: ^1.8.0
  uuid: ^4.4.2
  xml: ">=5.3.0 <7.0.0"
  yaml: ^3.1.0

dev_dependencies:
  coverage: ^1.0.2
  intl: ">=0.17.0 <0.19.0"
  lints: ^2.0.0
  mocktail: ^0.3.0
  test: ^1.21.0

  # internal package, used only in tests data
  # test_lints:
  #   path: ./test/resources/test_lints

executables:
  metrics:
