name: metrics_for_dart_code_plugin_loader
description: This pubspec determines the version of the analyzer plugin to load.
publish_to: none
version:

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  metrics_for_dart_code:
    git:
      url: "https://github.com/ladans-io/metrics_for_dart_code"

dev_dependencies:
  lints: ^1.0.1
